# Generated by Django 5.1.3 on 2025-01-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_authagencybridges_authagencyusers_bridge_earthquake_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='earthquake',
            table='earthquake',
        ),
    ]
