# Generated by Django 5.1.3 on 2025-01-15 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_earthquake_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='typhoon',
            table='typhoon',
        ),
    ]
