# Generated by Django 5.1.3 on 2025-02-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_typhoon_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherDailyHistoryData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('station_id', models.CharField(max_length=10, unique=True)),
                ('time', models.DateTimeField()),
                ('max_temperature', models.FloatField(blank=True, null=True)),
                ('up_temperature', models.FloatField(blank=True, null=True)),
                ('mid_temperature', models.FloatField(blank=True, null=True)),
                ('down_temperature', models.FloatField(blank=True, null=True)),
                ('min_temperature', models.FloatField(blank=True, null=True)),
                ('max_wind_speed', models.FloatField(blank=True, null=True)),
                ('up_wind_speed', models.FloatField(blank=True, null=True)),
                ('mid_wind_speed', models.FloatField(blank=True, null=True)),
                ('down_wind_speed', models.FloatField(blank=True, null=True)),
                ('min_wind_speed', models.FloatField(blank=True, null=True)),
                ('max_wind_direction', models.FloatField(blank=True, null=True)),
                ('up_wind_direction', models.FloatField(blank=True, null=True)),
                ('mid_wind_direction', models.FloatField(blank=True, null=True)),
                ('down_wind_direction', models.FloatField(blank=True, null=True)),
                ('min_wind_direction', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weather_dialy_history_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_direction', models.FloatField(blank=True, null=True)),
                ('precipitation', models.FloatField(blank=True, null=True)),
                ('acc_precipitation', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weather_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('station_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('deleted', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weather_data',
                'managed': False,
            },
        ),
    ]
