# Generated by Django 5.1.3 on 2025-02-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_weatherdailyhistorydata_weatherdata_weatherstation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='weatherdailyhistorydata',
            table='weather_daily_history_data',
        ),
    ]
