# Generated by Django 5.1.3 on 2025-01-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroupUrls',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_urls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('path', models.TextField(unique=True)),
                ('element', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'auth_url',
                'managed': False,
            },
        ),
    ]
